COMPETITION_LIST = "/api/competitions"
COMPETITION_DELETE = "/api/competitions/{competition_id:uuid}"
COMPETITION_DETAIL = "/api/competitions/{competition_id:uuid}"
COMPETITION_UPDATE = "/api/competitions/{competition_id:uuid}"
COMPETITION_CREATE = "/api/competitions"
